version: '3'

services:
  nginx:
    image: nginx:${NGINX_VER:-1.18}
    container_name: ld-proxy-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/includes:/etc/nginx/includes:ro
      - ./proxy/certs:/etc/nginx/certs:ro
    networks:
      - localhost

  docker-gen:
    image: jwilder/docker-gen:${DOCKER_GEN_VER:-0.7.3}
    container_name: ld-proxy-gen
#    user: '${PUID:-1000}:${PGID:-1000}'
    restart: always
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/includes:/etc/nginx/includes:ro
      - ./proxy/templates:/etc/docker-gen/templates:ro
    networks:
      - localhost
    entrypoint: /usr/local/bin/docker-gen -notify-sighup ld-proxy-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf